repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/psf/black
    rev: '22.10.0'
    hooks:
      - id: black
        files: '^brian2/.*\.pyi?$'
