name: Docker Multi-Arch Release Image CI

on:
  release:
    types: [ published ]
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  # Schedule a weekly build on Sunday at 3am
  # schedule:
  #   - cron: '0 3 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # https://github.com/actions/checkout/
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      # https://github.com/docker/metadata-action
      with:
        images: |
          briansimulator/brian
        flavor: latest=true
        tags: |
          # type=semver,pattern={{raw}}
          type=ref,event=tag
        labels: |
          org.opencontainers.image.title="Brian Docker Image"
          org.opencontainers.image.description="Docker image for Brian - a free, open source simulator for spiking neural networks"
          org.opencontainers.image.url=https://hub.docker.com/r/briansimulator/brian
          org.opencontainers.image.source=https://github.com/brian-team/brian2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-qemu-action
      with:
        platforms: 'amd64,arm64'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      # https://github.com/docker/setup-buildx-action
    - name: Login to DockerHub
      uses: docker/login-action@v3
      # https://github.com/docker/login-action
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push the Docker image
      uses: docker/build-push-action@v5
      # https://github.com/docker/build-push-action
      with:
        context: .
        file: docker/Dockerfile
        build-args: |
            'BASE_IMAGE_TAG=3.12-bookworm'
        platforms: 'amd64,arm64'
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}