name: Update metadata after release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        # Give the default GITHUB_TOKEN write permission to commit and push the
        # added or changed files to the repository.
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: python -m pip install cffconvert pyaml ruamel.yaml requests
      - name: Update metadata
        run: python dev/continuous-integration/update_zenodo_swh.py
      - name: Verify CITATION.cff
        run: cffconvert --validate
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: CITATION.cff README.md
          commit_message: |
            Update CITATION.cff and README.md with metadata from Zenodo/SWH 

            [ci skip]