name: Build and publish to TestPyPI or PyPI
on: [push, pull_request]

jobs:
  build-n-publish:
    name: Build wheels on ${{ matrix.os }} and publish to (Test)PyPI
    runs-on: ${{ matrix.os }}
    environment: release
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1
        with:
          output-dir: dist
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7"
          CIBW_ARCHS_WINDOWS: auto64
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_TEST_SKIP: '*_arm64 *_universal2:arm64'
          CIBW_SKIP: 'pp* *-musllinux_*'
          CIBW_TEST_COMMAND: python {project}/dev/continuous-integration/run_simple_test.py
          CIBW_TEST_REQUIRES: pytest
      - name: Publish distribution 📦 to Test PyPI
        if: github.ref == 'refs/heads/master' && github.repository == 'brian-team/brian2'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Publish distribution release 📦 to PyPI
        if: ${{ startsWith(github.ref, 'refs/tags') && github.repository == 'brian-team/brian2' }}
        uses: pypa/gh-action-pypi-publish@release/v1

  build-n-publish-linux:
    name: Build ${{ matrix.arch }} wheels on Linux and publish to (Test)PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    strategy:
      fail-fast: false
      matrix:
        arch: [ auto64, aarch64 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Build source tarball
        run: |
          python -m pip install --upgrade pip
          python -m pip install "cython>=0.29" oldest-supported-numpy setuptools versioneer
          python setup.py sdist --formats=gztar --with-cython --fail-on-error
        if: ${{ matrix.arch == 'auto64' }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1
        with:
          output-dir: dist
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7"
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_SKIP: 'pp* *-musllinux_*'
          CIBW_TEST_COMMAND: python {project}/dev/continuous-integration/run_simple_test.py
          CIBW_TEST_REQUIRES: pytest
      - name: Publish distribution 📦 to Test PyPI
        if: github.ref == 'refs/heads/master' && github.repository == 'brian-team/brian2'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Publish distribution release 📦 to PyPI
        if: ${{ startsWith(github.ref, 'refs/tags') && github.repository == 'brian-team/brian2' }}
        uses: pypa/gh-action-pypi-publish@release/v1
