name: Build and publish
on: [push, pull_request]

jobs:
  get_python_versions:
    name: "Determine Python versions"
    runs-on: ubuntu-latest
    outputs:
      min-python: ${{ steps.nep29.outputs.min-python }}
      max-python: ${{ steps.nep29.outputs.max-python }}
    steps:
      - name: "calculate versions according to NEP29"
        id: nep29
        uses: mstimberg/github-calc-nep29@v0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: [get_python_versions]
    name: Build 🎡 on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macOS-12, macOS-14 ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5
      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=${{ needs.get_python_versions.outputs.min-python }}"
          CIBW_ARCHS: auto64
          # Do not build for PyPy
          CIBW_SKIP: 'pp*'
          CIBW_TEST_COMMAND: python {project}/dev/continuous-integration/run_simple_test.py
          CIBW_TEST_REQUIRES: pytest
      - name: store distribution 📦
        uses: actions/upload-artifact@v4
        with:
          name: packages-other
          path: dist

  build-linux:
    needs: [get_python_versions]
    name: Build ${{ matrix.arch }} 🎡 and source 📦 on Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ auto64, aarch64 ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Build source tarball
        run: |
          python -m pip install --upgrade pip build
          python -m pip install "cython>=0.29" oldest-supported-numpy "setuptools>=61" "setuptools_scm[toml]>=6.2"
          python -m build --sdist --config-setting=--formats=gztar --config-setting=--with-cython --config-setting=--fail-on-error
        if: ${{ matrix.arch == 'auto64' }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5
      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=${{ needs.get_python_versions.outputs.min-python }}"
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_SKIP: 'pp* *-musllinux_aarch64'
          CIBW_TEST_COMMAND: python {project}/dev/continuous-integration/run_simple_test.py
          CIBW_TEST_REQUIRES: pytest
      - name: store distribution 📦
        uses: actions/upload-artifact@v4
        with:
          name: packages-linux
          path: dist

  deploy_dev:
    name: Publish development 📦 to TestPyPI
    runs-on: ubuntu-latest
    if: github.repository == 'brian-team/brian2' && github.ref == 'refs/heads/master'
    environment: development_release
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    needs:
      - build
      - build-linux
    steps:
      - name: load Linux distribution 📦
        uses: actions/download-artifact@v4
        with:
          name: packages-linux
          path: dist/
      - name: load other distribution 📦
        uses: actions/download-artifact@v4
        with:
          name: packages-other
          path: dist/
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  deploy:
    name: Publish release 📦 to PyPI
    runs-on: ubuntu-latest
    if: github.repository == 'brian-team/brian2' && startsWith(github.ref, 'refs/tags')
    environment: release
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    needs:
      - build
      - build-linux
    steps:
      - name: load Linux distribution 📦
        uses: actions/download-artifact@v4
        with:
          name: packages-linux
          path: dist/
      - name: load other distribution 📦
        uses: actions/download-artifact@v4
        with:
          name: packages-other
          path: dist/
      - name: Publish distribution release 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  
  build-docker:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # https://github.com/actions/checkout/
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      # https://github.com/docker/metadata-action
      with:
        images: |
          briansimulator/brian
        flavor: latest=true
        tags: |
          # type=semver,pattern={{raw}}
          type=ref,event=tag
        labels: |
          org.opencontainers.image.title="Brian Docker Image"
          org.opencontainers.image.description="Docker image for Brian - a free, open source simulator for spiking neural networks"
          org.opencontainers.image.url=https://hub.docker.com/r/briansimulator/brian
          org.opencontainers.image.source=https://github.com/brian-team/brian2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-qemu-action
      with:
        platforms: 'amd64,arm64'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      # https://github.com/docker/setup-buildx-action
    - name: Login to DockerHub
      uses: docker/login-action@v3
      # https://github.com/docker/login-action
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: load Linux distribution 📦
      uses: actions/download-artifact@v4
      with:
        name: packages-linux
        pattern: "*cp312*.whl"
        path: dist/
    - name: Build (and potentially push) the Docker image
      uses: docker/build-push-action@v5
      # https://github.com/docker/build-push-action
      with:
        context: .
        file: docker/Dockerfile
        build-args: |
            'BASE_IMAGE_TAG=3.12-bookworm'
        platforms: 'amd64,arm64'
        push: github.repository == 'brian-team/brian2' && startsWith(github.ref, 'refs/tags')
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
