name: Build and publish to TestPyPI or PyPI
on: [push, pull_request]

jobs:
  build-n-publish:
    name: Build wheels on ${{ matrix.os }} and publish to (Test)PyPI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2019, macOS-10.15 ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install cibuildwheel & dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==1.9.0
      - name: Build source tarball (only on Linux)
        run: python setup.py sdist --formats=gztar --with-cython --fail-on-error
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_BEFORE_BUILD: pip install "cython>=0.29" numpy>=1.15 setuptools
          CIBW_BUILD_VERBOSITY: 1
      - name: Publish distribution 📦 to Test PyPI
        if: ${{ ! startsWith(github.ref, 'refs/tags') }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution release 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
