name: TestSuite

on: [push,pull_request]

jobs:
  testing-ubuntu:
    name: TestSuite on Ubuntu-20.04
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Add conda to PATH
        run: echo "##vso[task.prependpath]$CONDA/bin"
      - name: Setup Conda Environment
        run: conda create --prefix $HOME/test_env -c conda-forge --yes --quiet python=$(python.version) pip pytest
        