name: TestSuite

on: [push, pull_request]

jobs:
  testing-ubuntu:
    name: TestSuite on Ubuntu-20.04
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Conda Environment
        run: |
          conda create --prefix $HOME/test_env -c conda-forge --yes --quiet python=3.8 pip pytest
          conda init bash

      - name: Install Brian2
        run: |
          conda install -n test_env --quiet --yes -c conda-forge pytest cython sympy future pyparsing numpy jinja2 six scipy sphinx gsl coverage
          pip install .

      - name: Run Tests
        run: |
          conda activate test_env
          cd $GITHUB_WORKSPACE
          coverage run --rcfile=$GITHUB_WORKSPACE/.coveragerc $GITHUB_WORKSPACE/$SCRIPT_NAME
          coverage report -m
        env:
          SCRIPT_NAME: dev/continuous-integration/run_test_suite.py
          AGENT_OS: ${{runner.os}}
          SPLIT_RUN: 1
      
      - name: Upload coverage data to coveralls
        run: |
          conda activate test_env
          conda install --quiet --yes coveralls
          coveralls --service=github --rcfile=$GITHUB_WORKSPACE/.coveragerc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ github.job }}
          COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: testing-ubuntu
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
