name: TestSuite

on: [push, pull_request]

jobs:
  testing-ubuntu:
    name: TestSuite on Ubuntu-20.04
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Conda and Python
        uses: s-weigand/setup-conda@v1.0.5
        with:
          python-version: 3.8
          conda-channels: conda-forge

      - name: Setup Conda Environment
        run: conda create --prefix $HOME/test_env -c conda-forge --yes --quiet python=3.8 pip pytest

      - name: Install Brian2
        run: |
          source activate $HOME/test_env   
          conda install --quiet --yes -c conda-forge pytest cython sympy future pyparsing numpy jinja2 six scipy sphinx gsl coverage
          pip install .

      - name: Run Tests
        run: |
          source activate $HOME/test_env
          cd $GITHUB_WORKSPACE
          coverage run $GITHUB_WORKSPACE/$SCRIPT_NAME
        env:
          SCRIPT_NAME: dev/continuous-integration/run_test_suite.py
          AGENT_OS: ${{runner.os}}
          COVERAGE_RCFILE: ${{github.workspace}}/.coveragerc
      
      - name: Upload coverage data to coveralls
        run: |
          pip install coveralls
          pwd
          ls -a

 