name: TestSuite

on: [push, pull_request]

jobs:
  testing-ubuntu:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python37_runtime_1
            python-version: 3.7
            script-name: dev/continuous-integration/run_test_suite.py
            standalone: false
            split-run: 1
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Conda and Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: 'test_env'
          python-version: ${{ matrix.python-version }}

      - name: Install Brian2 and dependencies
        run: |
          conda install -n test_env --quiet --yes -c conda-forge pip pytest cython sympy future pyparsing numpy jinja2 six scipy sphinx gsl coverage
          pip install .

      - name: Run Tests
        run: |
          cd  $GITHUB_WORKSPACE/.. # move out of the workspace to avoid direct import
          coverage run --rcfile=$GITHUB_WORKSPACE/.coveragerc $GITHUB_WORKSPACE/$SCRIPT_NAME
        env:
          SCRIPT_NAME: ${{ matrix.script-name }}
          AGENT_OS: ${{runner.os}}
          SPLIT_RUN: ${{ matrix.split-run }}
          STANDALONE: ${{ matrix.standalone }}
      
      - name: Upload coverage data to coveralls
        run: |
          cp  $GITHUB_WORKSPACE/../.coverage .
          conda install --quiet --yes coveralls
          coveralls --service=github --rcfile=$GITHUB_WORKSPACE/.coveragerc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ github.job }}
          COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: testing-ubuntu
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
